const content = {
    tab1: 'Personal Details',
    tab2: 'Company Details',
    tab3: 'Email Verification',
    personalDetails_header1: 'Add your personal details',
    personalDetails_header2: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    personalDetails_fullName: 'Full Name',
    personalDetails_gender: 'Gender',
    gender_male: 'Male',
    gender_female: 'Female',
    gender_others: 'Others',
    personalDetails_country: 'Country',
    personalDetails_countryLabel: 'Select Country',
    personalDetails_state: 'State',
    personalDetails_stateLabel: 'Select State',
    personalDetails_phoneNumber: 'Phone Number',
    button_next: 'Next',
    button_verify: 'Verify',
    button_back: 'Back',
    personalDetails_footerText: 'Already have an account?',
    personalDetails_footerTextLogin: 'Log in',
    companyDetails_header1: 'Add your company details',
    companyDetails_header2: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    companyDetails_imageLabel: 'Upload your company logo',
    companyDetails_companyName: 'Company Name',
    companyDetails_emailId: 'Email ID',
    companyDetails_jobTitle: 'Job Title',
    companyDetails_expireance: 'Years of Expireance',
    companyDetails_term1: 'I accept the',
    companyDetails_term2: 'Tearms and Conditions',
    emailVerification_header1: 'Enter your OTP',
    emailVerification_header2: 'For your security, we need to verify your identity. We sent a 5-digit code to ',
    emailVerification_header3: '. Please enter it below.',
    emailVerification_otpLabel: 'Enter your code',
    emailVerification_resendOtpLabel: 'Resend OTP',
    emailVerification_footer: 'Didn’t receive the email?  Check your spam filter for an email from',
    apiAddSuccess: 'Data saved successfully',
    apiUpdateSuccess: 'Data updated successfully',
    apiIssue: 'Something went wrong',
    invalidEmail: 'Invalid email id',
    otpSuccess: 'OTP verified successfully',
    otpFailed: 'OTP verification failed',
    fileFormat: 'File formate is not supported',
}

export default content
