const reduxDispatchType = {
    CREATE_PERSONAL_DETAILS: 'CREATE_PERSONAL_DETAILS',
    CREATE_COMPANY_DETAILS: 'CREATE_COMPANY_DETAILS',
    EMAIL_VERIFICATION: 'EMAIL_VERIFICATION'
}

export default reduxDispatchType